lsi: false
safe: true
source: https://github.com/Nomenteam/nomenteam.github.io
theme: just-the-docs
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
